include:
  - https://invent.kde.org/sysadmin/ci-tooling/raw/master/invent/ci-before.yml
  - https://invent.kde.org/sysadmin/ci-tooling/raw/master/invent/ci-extragear-linux.yml

android:
  variables:
    CI_TOOLING: /home/user/ci-tooling

  stage: build
  image: nicolasfella/android-sdk

  artifacts:
    paths:
      - "*.apk"

  script:
    - cd /home/user
    - /opt/helpers/build-kde-dependencies alligator
    - APK_ARGS=`python3 /opt/helpers/get-apk-args.py $CI_PROJECT_DIR`
    - /opt/helpers/build-cmake alligator $CI_PROJECT_DIR $APK_ARGS -DANDROID_APK_OUTPUT_DIR=$CI_PROJECT_DIR
    - pushd build-arm/alligator
    - make create-apk
    - popd
    - pushd build-arm64/alligator
    - make create-apk
    - popd
