include:
  - https://invent.kde.org/sysadmin/ci-tooling/raw/master/invent/ci-before.yml
  - https://invent.kde.org/sysadmin/ci-tooling/raw/master/invent/ci-extragear-linux.yml

android:
  variables:
    CI_TOOLING: /home/user/ci-tooling

  stage: build
  image: nicolasfella/android-sdk

  script:
    - cd /home/user
    - /opt/helpers/build-kde-dependencies alligator
    - APK_ARGS=`python3 /opt/helpers/get-apk-args.py .`
    - build-kde-project alligator Applications $APK_ARGS
    - /opt/helpers/create-apk alligator
