include:
  - https://invent.kde.org/sysadmin/ci-tooling/raw/master/invent/ci-before.yml
  - https://invent.kde.org/sysadmin/ci-tooling/raw/master/invent/ci-extragear-linux.yml

android:
  variables:
    CI_TOOLING: /home/user/ci-tooling

  stage: build
  image: nicolasfella/android-sdk

  artifacts:
    paths:
      - /home/user/build-arm/alligator/*.apk

  script:
    - SRCDIR=$(pwd)
    - pushd /home/user
    - /opt/helpers/build-kde-dependencies alligator
    - APK_ARGS=`python3 /opt/helpers/get-apk-args.py $SRCDIR`
    - /opt/helpers/build-cmake alligator $SRCDIR $APK_ARGS
    - pushd /home/user/build-arm/alligator
    - make create-apk
    - popd
    - pushd /home/user/build-arm64/alligator
    - make create-apk
    - popd
