# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux/Qt6', 'Linux/Qt6Next', 'Android/Qt6', 'FreeBSD/Qt6', 'Windows/Qt6']
  'require':
    'frameworks/extra-cmake-modules': 'Frameworks/6.24'
    'frameworks/kcolorscheme': 'Frameworks/6.24'
    'frameworks/kcoreaddons': 'Frameworks/6.24'
    'frameworks/kconfig': 'Frameworks/6.24'
    'frameworks/ki18n': 'Frameworks/6.24'
    'frameworks/kirigami': 'Frameworks/6.24'
    'frameworks/syndication': 'Frameworks/6.24'
    'libraries/kirigami-addons': 'v1.11.0'

- 'on': ['Linux/Qt6/Shared', 'Linux/Qt6Next/Shared', 'FreeBSD/Qt6/Shared', 'Windows/Qt6/Shared']
  'require':
    'frameworks/qqc2-desktop-style': 'Frameworks/6.24'

- 'on': ['Linux/Qt6/Static']
  'require':
    'plasma/qqc2-breeze-style': '@latest-kf6'

Options:
  require-passing-tests-on: [ '@all' ]
  run-qmllint: true
